insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('2G61T5S30E9613008', 'Bonsey''s Hollyfern', 'Gorman''s Saxifrage', 1);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WAUEF98E58A252080', 'White False Hellebore', 'Fairyduster', 2);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WAUEF98E58A252080', 'Thickstem Wild Cabbage', 'Santa Cruz Water-lily', 3);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WAUFEBFM6CA036627', 'Pore Lichen', 'Fairyduster', 4);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('JN1CV6EKXCM178509', 'Nettle-leaf Soldier', 'Gorman''s Saxifrage', 5);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('2G61T5S30E9613008', 'Bonsey''s Hollyfern', 'Santa Cruz Water-lily', 6);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WAUEF78E48A594494', 'White False Hellebore', 'Shrubland Beggarticks', 7);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('JN1CV6EKXCM178509', 'Myrobalan', 'Gorman''s Saxifrage', 8);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WBA3B9C52DF386729', 'Hudson Bay Sedge', 'Brazilian Morning-glory', 9);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WAUEF98E58A252080', 'Muskflower', 'Brazilian Morning-glory', 10);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WAUEF78E48A594494', 'Myrobalan', 'Gorman''s Saxifrage', 11);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('JN8AE2KP7E9297237', 'White False Hellebore', 'Gorman''s Saxifrage', 12);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('JH4KC1F75EC057745', 'Red Hempnettle', 'Amur Maackia', 13);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WBA3C1C5XFP154729', 'Castle Lake Bedstraw', 'Brazilian Morning-glory', 14);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('2G61T5S30E9613008', 'Castle Lake Bedstraw', 'Florida Feathershank', 15);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('SCFLDCFP3EG994456', 'Nettle-leaf Soldier', 'Santa Cruz Water-lily', 16);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('WBA3C1C5XFP154729', 'Myrobalan', 'Amur Maackia', 17);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('KMHGH4JH3FU887772', 'Snow Dwarf-primrose', 'Thinfruit Sedge', 18);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('KNAFU6A22D5158119', 'Indian Warrior', 'Shrubland Beggarticks', 19);
insert into tp.entrega_proveeduria (matricula_transportista, nombre_productor, nombre_proveedor, id) values ('2HNYD18242H984426', 'Red Hempnettle', 'Salt Heliotrope', 20);
