insert into tp.estacion_primaria (nombre, nro_transformadores) values ('American black bear', 19);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Turkey, wild', 9);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Openbill, asian', 12);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Booby, blue-footed', 1);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Deer, white-tailed', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Arctic ground squirrel', 14);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Red-capped cardinal', 18);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('American crow', 17);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Chimpanzee', 14);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Beaver, american', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Coyote', 13);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Andean goose', 19);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Goose, egyptian', 18);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Possum, pygmy', 9);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('American black bear', 10);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('White-eye, pale', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Yellow-headed caracara', 15);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Boubou, southern', 8);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Zebra, plains', 20);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Otter, oriental short-clawed', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Peregrine falcon', 7);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Canada goose', 7);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Bird, black-throated butcher', 11);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Eagle, pallas''s fish', 4);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Fox, bat-eared', 12);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('White-browed sparrow weaver', 2);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Bleu, blue-breasted cordon', 2);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Grey heron', 17);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Lily trotter', 16);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Oriental short-clawed otter', 19);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Shrike, crimson-breasted', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Red-breasted nuthatch', 10);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Iguana, land', 7);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Goose, cereopsis', 14);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Tern, arctic', 8);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Red-necked phalarope', 13);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Red brocket', 4);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('African elephant', 16);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Heron, striated', 17);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Gull, lava', 3);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Whip-tailed wallaby', 3);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Urial', 16);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Tiger', 16);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Banded mongoose', 8);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Mallard', 15);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Monitor, water', 6);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Brown and yellow marshbird', 13);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Bat-eared fox', 4);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Grey-footed squirrel', 17);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Sheep, american bighorn', 16);
