insert into tp.transportista (nombre, matricula) values ('Hairy Townsend Daisy', '1FTMF1E8XAK316657');
insert into tp.transportista (nombre, matricula) values ('Everblooming Ixora', '5GAKRAED6CJ253159');
insert into tp.transportista (nombre, matricula) values ('Ambiguous Aloina Moss', '1FTWX3D57AE940195');
insert into tp.transportista (nombre, matricula) values ('Fragile Onion', '1FTWF3D58AE014262');
insert into tp.transportista (nombre, matricula) values ('Seashore Plantain', 'WA1LMAFE8BD798585');
insert into tp.transportista (nombre, matricula) values ('Gray Pubescent Plantain', 'KMHGC4DD8EU019708');
insert into tp.transportista (nombre, matricula) values ('Sedge', 'WBA3B1G55FN714620');
insert into tp.transportista (nombre, matricula) values ('Baneberry', '2FMPK3J95FB028447');
insert into tp.transportista (nombre, matricula) values ('Liddon Sedge', '1C3CCBBB8CN404819');
insert into tp.transportista (nombre, matricula) values ('Alpine Nerve Sedge', 'WBAUN7C59BV947785');
insert into tp.transportista (nombre, matricula) values ('Florida False Sunflower', '1G4HP54K64U173975');
insert into tp.transportista (nombre, matricula) values ('San Joaquin Tarweed', '1N6BF0KM0FN728918');
insert into tp.transportista (nombre, matricula) values ('Tripleleaf Morning-glory', '2C4RDGEG8DR517200');
insert into tp.transportista (nombre, matricula) values ('Desert Deathcamas', 'WBAYP1C52ED604755');
insert into tp.transportista (nombre, matricula) values ('Nearlyblack Sedge', '2T1BU4EEXBC134466');
insert into tp.transportista (nombre, matricula) values ('Cup Lichen', 'WDDNG9FB6DA962887');
insert into tp.transportista (nombre, matricula) values ('Galax', '4T1BK1EB3FU337987');
insert into tp.transportista (nombre, matricula) values ('Orange Daisy', 'WBA5B1C51FD808742');
insert into tp.transportista (nombre, matricula) values ('Glossy Abelia', '3CZRE3H37AG949609');
insert into tp.transportista (nombre, matricula) values ('Broom Snakeweed', '2C4RDGCG9CR242258');
