insert into tp.estacion_primaria (nombre, nro_transformadores) values ('American black bear', 19);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Turkey, wild', 9);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Openbill, asian', 12);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Booby, blue-footed', 1);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Deer, white-tailed', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Arctic ground squirrel', 14);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Red-capped cardinal', 18);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('American crow', 17);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Chimpanzee', 14);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Beaver, american', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Coyote', 13);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Andean goose', 19);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Goose, egyptian', 18);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Possum, pygmy', 9);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('American black bear', 10);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('White-eye, pale', 5);
insert into tp.estacion_primaria (nombre, nro_transformadores) values ('Yellow-headed caracara', 15);
