insert into tp.transportista (nombre, matricula) values ('Stiffleaf False Goldenaster', '5TDBKRFH8FS511823');
insert into tp.transportista (nombre, matricula) values ('Candlewood', 'WAUEF78E48A594494');
insert into tp.transportista (nombre, matricula) values ('Lilythorn', 'KNAFU6A22D5158119');
insert into tp.transportista (nombre, matricula) values ('Fontinalis Moss', '2HNYD18242H984426
 Pencilmark');
insert into tp.transportista (nombre, matricula) values ('Pencilmark Lichen', 'WAUET48H06K990351');
insert into tp.transportista (nombre, matricula) values ('Rio Grande Phlox', 'JH4KC1F75EC057745');
insert into tp.transportista (nombre, matricula) values ('Shasta Knotweed', 'WAUFEBFM6CA036627');
insert into tp.transportista (nombre, matricula) values ('Snowqueen', 'JN1CV6EKXCM178509');
insert into tp.transportista (nombre, matricula) values ('Bindweed Dwarf Morning-glory', 'JN8AE2KP7E9297237');
insert into tp.transportista (nombre, matricula) values ('California Silverbush', 'KMHGH4JH3FU887772');
insert into tp.transportista (nombre, matricula) values ('Lurid Fishscale Lichen', 'WBA3B9C52DF386729');
insert into tp.transportista (nombre, matricula) values ('Largeflower Crested Coralroot', '2G61T5S30E9613008');
insert into tp.transportista (nombre, matricula) values ('White Wormwood', 'WVWAN7AN3DE933179');
insert into tp.transportista (nombre, matricula) values ('Jamaican Pepper', 'WVWGU7AN6CE947783');
insert into tp.transportista (nombre, matricula) values ('Cattail Grass', 'WAULT68E52A697389');
insert into tp.transportista (nombre, matricula) values ('Ballmustard', 'WAUEF98E58A252080');
insert into tp.transportista (nombre, matricula) values ('Fedex', 'WAUNF78P57A218970');
insert into tp.transportista (nombre, matricula) values ('Nutrush', 'SCFLDCFP3EG994456');
insert into tp.transportista (nombre, matricula) values ('Cup Lichen', 'WBA3C1C5XFP154729');
